const ADMIN_ACCOUNT = 'ADMIN'
const CLIENT_ACCOUNT = 'CLIENT'
const SUPPORT_ACCOUNT = 'SUPPORT'
const DOCTOR_ENFORCEMENT_ACCOUNT = 'DOCTOR_ENFORCEMENT'

module.exports= {ADMIN_ACCOUNT, CLIENT_ACCOUNT, SUPPORT_ACCOUNT,DOCTOR_ENFORCEMENT_ACCOUNT}

